language: node_js

node_js:
  - 7.7

sudo: required
services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t pandres95/evolutio-led .;
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push pandres95/evolutio-led;
    fi
